#locate your libmysqlclient_r.so

all:
	gcc -g -O0 -Wall -o seh seh.c -I/Users/kimnin/develop/server/mysql/include -L/Users/kimnin/develop/server/mysql/lib -lmysqlclient_r -lpthread

clean:
	rm -rf *.o relayfetch
